### PR TITLE
non-root user for docker and k8s

### LINKED ISSUE #43: Upgrade go build versions
See:
https://hub.docker.com/_/golang?tab=tags
https://hub.docker.com/r/goboring/golang/tags

### LINKED ISSUE #44: Docker image with non-root user
## What's missing?
The docker process (for the Apigee adapter) runs as a root user. This FR is to create a non-root user and run as that user.

## Your preferred solution
Preference is to create an `apigee` user and install the product binary in `/opt/apigee`. Update the deployment spec (samples) with a PodSecurityContext: runAsUser, runAsGroup, runAsNonRoot

### PR DESCRIPTION
**Pull request by theganyo**
update standard go to 1.15.0
update goboring to 1.14.6
closes #43 
closes #44

### CODE REVIEW

**Comment by rockspore** [comment]
Why was it closed?

**Comment by theganyo** [comment]
Sorry about that. There was an inadvertent change included and didn't want it merged. It's ok now.

**Comment by theganyo** [comment]
Be aware: The existing docker images will not deploy these new specs: `samples/istio/hybrid-apigee-remote-service-envoy.yaml` and `samples/istio/saas-apigee-remote-service-envoy.yaml`

**Comment by rockspore** [comment]
> Be aware: The existing docker images will not deploy these new specs: `samples/istio/hybrid-apigee-remote-service-envoy.yaml` and `samples/istio/saas-apigee-remote-service-envoy.yaml`

Would they fail to start (or become ready) or would they still run as root?

**Comment by theganyo** [comment]
They will fail to run.  The restrictions will prevent K8s from starting the image.

**Pull request merged**
